#!/usr/bin/env bash 

# code to scan the bibtex file for discussion papers 
# which are likely to contain authors 
# names that will not be picked up by the sed 
# dictionary I’ve created so far. 

# TODO: drop in the call to the bibfix file. 
# TODO: sketch out how to modularize the sed calls so
#       that a user who specializes in bioinformatics can use only what they need.  
#       to do this we might look into arguments at invocation like —stats —bionif etc 


# checks if the words “discussion” and “by” are in the file

# TODO: add in a check for Rejoinder papers as well 

lines=`sed -n /[Dd][Ii][Ss][Cc][Uu][Ss][Ss][Ii][Oo][Nn].*[Bb][Yy]/p $1 | wc -l `
# $(($lines>0))

#this returns 1 if there are more than 0 lines and 0 otherwise. 

if [ $(($lines>0)) -gt 0 ]
    then 
    echo You have at least one entry with a Rejoinder, or Discussion paper. You may want to manually check these entries because they often contain Author’s names.
	echo Some of these potential entries are at lines:
	echo `grep -n [Dd][Ii][Ss][Cc][Uu][Ss][Ss][Ii][Oo][Nn].*[Bb][Yy] test_case1.bib | awk -F: '{ print $1 }'`
    else
    echo It does not appear you have Rejoinder or discussion papers. 
    fi
